name: Hola Mundo
on:
  push: 
    branches: 
     - 'main'
  pull_request:
    branches: 'main'
jobs:
    hola-mundo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node 
              uses: actions/setup-node@v4
              with:
                node-version: '21'
            - name: Run the code
              run: node holaMundo.js
    
