name: Hola Mundo
on:
  push: 
    branches: 
      'main'
  pull_request:
    branches: 'main'
jobs:
    hola-mundo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run hola-mundo.js
              run: node holaMundo.js