name: Hola Mundo
on: [push]
jobs:
    hola-mundo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run hola-mundo.js
              run: node holaMundo.js 
              with: 
              node-version: '18'
